# Generated by Django 5.2.1 on 2025-05-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_canvasstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
