# Generated by Django 5.2.1 on 2025-05-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_room_is_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="password",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
