# ---------- docker-compose.yml ----------

version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env # contains SECRET_KEY, DEBUG, ALLOWED_HOSTS, etc.
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
